added chart for pdf-generator
Altinn/altinn-studio-charts pull request #17
Opened 2022-12-02 09:52 UTC by acn-sbuad

## Description
Added helm chart for pdf generator based on browserless chrome .

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

2022-12-02 11:18 UTC, tjololo requested changes
For role, rolebinding and serviceaccount we are hardcoding the name, but for the other we depend on the name of the chart/deployment through the helpers. I think we should be consistent in how we name the resources. Also on these resources namespace is set to pdf but not on the other this could lead to the resources being deployed in different namespaces.

2022-12-02 11:18 UTC, tjololo commented on charts/pdf-generator/templates/middleware.yaml
> +{{- range $middleware := .Values.middlewares }}
Is this file necessary?

2022-12-02 11:18 UTC, tjololo commented on charts/pdf-generator/values.yaml
> +  tag: latest
It's recomended to not depend on latest as we have no control if there are breaking changes in latest. Should we rather depend on a pinned version and upgrade the chart when new versions are available?

2022-12-02 11:21 UTC, tjololo commented on charts/pdf-generator/values.yaml
> +  pullPolicy: Always
Should we change the default pullPolicy to IfNotPresent?

2022-12-02 12:01 UTC, acn-sbuad commented on charts/pdf-generator/values.yaml
> +  pullPolicy: Always
```suggestion
  pullPolicy: IfNotPresent
```

2022-12-02 12:08 UTC, acn-sbuad commented on charts/pdf-generator/values.yaml
> +  tag: latest
```suggestion
  tag: 1-puppeteer-19.2.2
```

2022-12-02 13:34 UTC, tjololo commented on charts/pdf-generator/templates/deployment.yaml
> +  namespace: {{ .Values.namespace }}
Sorry my bad! I just remembered that it's possible to use a built in variable in helm to control namespace, we can then use: `helm install --namespace whatever` to control the namespace it should be installed

```suggestion
  namespace: {{ Release.Namespace }}
```

2022-12-05 09:34 UTC, tjololo approved these changes

2022-12-05 09:34 UTC, tjololo commented on charts/pdf-generator/values.yaml
> +namespace: pdf
Remove unused variable
```suggestion
```

2022-12-05 16:29 UTC, merged